// Generated by hand from navy-backend Pydantic schemas.
// All backend responses are wrapped in GenericResponse { success, message, data }
// — the client unwraps `data` automatically.

export type UUID = string;

export interface ApiEnvelope<T> {
  success: boolean;
  message: string;
  data: T | null;
}

export type Paginated<T> = {
  items: T[];
  total: number;
  page: number;
  page_size: number;
};

// ---------------------------------------------------------------- Auth
export interface BackendUser {
  id: UUID;
  service_number: string;
  name: string;
  rank: string;
  unit: string;
  role:
    | "trainee"
    | "instructor"
    | "evaluator"
    | "doctrine"
    | "fleet"
    | "admin"
    | "maintainer";
  cohort_id?: string | null;
  classification_clearance: string;
  is_active: boolean;
  last_login: string | null;
  created_at: string;
  updated_at?: string;
}

export interface LoginResponse {
  access_token: string;
  refresh_token: string;
  token_type: string;
  expires_in: number;
  user: BackendUser;
}

export interface RefreshResponse {
  access_token: string;
  token_type: string;
  expires_in: number;
}

// ---------------------------------------------------------------- Users
export interface CompetencySummary {
  domain: string;
  average_score: number;
  skill_count: number;
  last_assessed: string;
}

export interface UserAnalytics {
  user_id: UUID;
  name: string;
  rank: string;
  competencies: CompetencySummary[];
  total_sessions: number;
  certifications_count: number;
}

// ---------------------------------------------------------------- Digital Twin
export interface Ship {
  ship_id: string;
  name: string;
  class: string;
  hull_number: string;
  commissioned: string;
  displacement_tonnes: number;
  home_port: string;
  status: string;
}

export interface ShipTwinState {
  ship_id: string;
  name: string;
  timestamp: string;
  position: { lat: number; lon: number };
  heading_deg: number;
  speed_knots: number;
  depth_m: number;
  systems: Record<string, Record<string, unknown>>;
  crew_readiness: number;
  readiness_state: string;
}

export interface SystemGraph {
  ship_id: string;
  nodes: { id: string; label: string; type: string }[];
  edges: { from: string; to: string; type: string }[];
}

// ---------------------------------------------------------------- Doctrine
export interface DoctrineDoc {
  id: UUID;
  title: string;
  domain: string;
  version: string;
  content_hash: string | null;
  file_ref: string | null;
  embedded_at: string | null;
  approved_by: UUID | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface DoctrineGrounding {
  document_id: UUID;
  title: string;
  domain: string;
  version: string;
  usage_count: number;
  last_used: string | null;
}

// ---------------------------------------------------------------- Scenarios
export interface Scenario {
  id: UUID;
  title: string;
  domain: string;
  difficulty: string;
  doctrine_version: string;
  definition: Record<string, unknown>;
  created_by: UUID;
  estimated_duration_minutes: number;
  tags: string[];
  is_archived: boolean;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------- Sessions
export interface TelemetryEntry {
  timestamp: string;
  event_type: string;
  data?: Record<string, unknown>;
  payload?: Record<string, unknown>;
  injected_by?: string;
}

export interface TrainingSession {
  id: UUID;
  scenario_id: UUID;
  trainee_id: UUID;
  instructor_id: UUID | null;
  status: "active" | "paused" | "completed" | "aborted";
  started_at: string | null;
  ended_at: string | null;
  score: Record<string, unknown> | null;
  telemetry_log: TelemetryEntry[];
  replay_ref: string | null;
  instructor_notes: string | null;
  created_at: string;
}

// ---------------------------------------------------------------- Analytics
export interface DomainScore {
  domain: string;
  average_score: number;
  skill_breakdown: Record<string, number>;
  session_count: number;
  trend: "improving" | "declining" | "stable";
  last_assessed: string;
}

export interface TraineeAnalytics {
  user_id: UUID;
  name: string;
  rank: string;
  domains: DomainScore[];
  overall_score: number;
  sessions_completed: number;
  certifications_earned: number;
}

export interface CohortMember {
  user_id: UUID;
  name: string;
  rank: string;
  overall_score: number;
  sessions_completed: number;
  status: string;
}

export interface CohortAnalytics {
  cohort_id: UUID;
  cohort_name: string;
  member_count: number;
  average_score: number;
  top_domain: string;
  weakest_domain: string;
  members: CohortMember[];
}

export interface FleetAnalytics {
  total_trainees: number;
  total_sessions: number;
  average_fleet_score: number;
  domain_performance: Record<string, number>;
  certifications_this_month: number;
  active_sessions: number;
}

export interface PredictiveTrend {
  domain: string;
  current_score: number;
  predicted_score_30d: number;
  predicted_score_90d: number;
  trajectory: "positive" | "negative" | "flat";
  confidence: number;
  recommendations: string[];
}

export interface PredictiveAnalytics {
  user_id: UUID;
  predictions: PredictiveTrend[];
  note?: string;
}

export interface DomainWeakness {
  domain: string;
  average_score: number;
  weakest_skills: { skill: string; average_score: number }[];
  recommended_focus: string;
  trainee_count: number;
}

// ---------------------------------------------------------------- Certifications
export interface Certification {
  id: UUID;
  user_id: UUID;
  cert_type: string;
  domain: string;
  issued_by: UUID;
  issued_at: string;
  valid_until: string | null;
  is_revoked: boolean;
  revoked_at: string | null;
  revoked_by: UUID | null;
  evidence_session_ids: string[];
  certificate_number: string;
}

export interface PendingCertification {
  trainee_id: UUID;
  trainee_name: string;
  rank: string;
  domain: string;
  completed_session_id: UUID;
  score: Record<string, unknown> | null;
}

export interface CertVerification {
  certificate_number: string;
  is_valid: boolean;
  issued_to: string;
  issued_to_rank: string;
  domain: string;
  cert_type: string;
  issued_at: string;
  valid_until: string | null;
  is_revoked: boolean;
  revoked_reason: string | null;
}

// ---------------------------------------------------------------- AI
export interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

export interface ChatResponse {
  response: string;
  model: string;
  interaction_id: UUID;
}

export interface AssessResponse {
  score: number;
  feedback: string;
  competency_tags: string[];
  confidence: number;
  interaction_id: UUID;
}

export interface AIAuditEntry {
  id: UUID;
  user_id: UUID;
  session_id: UUID | null;
  interaction_type: string;
  doctrine_version_used: string | null;
  confidence: number | null;
  overridden_by: UUID | null;
  override_reason: string | null;
  timestamp: string;
}

export interface AIModelInfo {
  model_name: string;
  provider: string;
  status: string;
  available: boolean;
  available_models: string[];
  model_in_use: string;
}

// ---------------------------------------------------------------- T2V
export interface T2VJob {
  status: string;
  progress?: number;
  message?: string;
  error?: string;
  question?: string;
  domain?: string;
  video_url?: string;
  session_id?: string;
  [key: string]: unknown;
}

export interface T2VModule {
  [key: string]: unknown;
}

// ---------------------------------------------------------------- Documentation
export interface DocumentationTopic {
  id: UUID;
  title: string;
  domain: string;
  description: string | null;
  content_markdown: string | null;
  example_interactive: string | null;
  created_by: UUID | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}


// ---------------------------------------------------------------- System
export interface ServiceStatus {
  name: string;
  status: "healthy" | "degraded" | "offline";
  latency_ms: number | null;
  details?: string;
}

export interface HealthMatrix {
  overall: string;
  services: ServiceStatus[];
  checked_at: string;
}

export interface SystemMetrics {
  cpu_percent: number;
  memory_percent: number;
  disk_percent: number;
  active_sessions: number;
  total_users: number;
  db_connections: number;
  uptime_seconds: number;
  collected_at: string;
}

export interface SystemAuditEntry {
  id: string;
  timestamp: string;
  user_id: string;
  action: string;
  resource: string;
  result: string;
  overridden?: boolean;
}
