"use client";

import { motion } from "framer-motion";
import { Bell, CheckCheck, BrainCircuit, Activity, Award, Shield, AlertTriangle, Settings } from "lucide-react";
import { GlassPanel } from "@/components/ui/glass-panel";
import { StatusBadge } from "@/components/ui/status-badge";
import { staggerContainer, fadeInUp } from "@/animations/variants";

const notifications = [
  { icon: AlertTriangle, title: "Session CIC-012 -- Trainee hesitation detected", desc: "AI Instructor flagged repeated hesitation during track classification", time: "2m ago", read: false, type: "alert" },
  { icon: BrainCircuit, title: "AI Insight: CIC Track Management weakness", desc: "3 trainees in Batch 2024-B showing repeated misclassification errors", time: "15m ago", read: false, type: "ai" },
  { icon: Activity, title: "Scenario DC-FIRE-07 approval pending", desc: "Generated by Scenario Engine -- awaiting instructor review", time: "1h ago", read: false, type: "scenario" },
  { icon: Shield, title: "Digital Twin sync completed", desc: "INS Vikrant model v3.2 successfully synced across all stations", time: "2h ago", read: true, type: "system" },
  { icon: Award, title: "Certification milestone reached", desc: "CPO M. Singh completed Engineering Fault Isolation certification", time: "3h ago", read: true, type: "certification" },
  { icon: BrainCircuit, title: "AI model v2.4.1 deployed", desc: "Cognitive Digital Twin updated with latest calibration data", time: "5h ago", read: true, type: "system" },
  { icon: Activity, title: "Session BRM-046 completed", desc: "LT S. Reddy scored 85 in COLREGS Head-On scenario", time: "6h ago", read: true, type: "session" },
];

const typeColors: Record<string, string> = { alert: "text-aegis-red", ai: "text-aegis-purple", scenario: "text-aegis-amber", system: "text-aegis-cyan", certification: "text-aegis-gold", session: "text-aegis-green" };

export default function NotificationsPage() {
  return (
    <motion.div variants={staggerContainer} initial="initial" animate="animate" className="space-y-6">
      <motion.div variants={fadeInUp} className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-aegis-cyan to-aegis-blue flex items-center justify-center">
            <Bell className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="font-display text-2xl font-bold text-aegis-white tracking-wide">Notifications</h1>
            <p className="font-heading text-sm text-aegis-mist tracking-wider mt-0.5">3 unread notifications</p>
          </div>
        </div>
        <div className="flex gap-3">
          <button className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-heading text-aegis-cyan hover:bg-white/[0.04] cursor-pointer"><CheckCheck className="w-3.5 h-3.5" />Mark all read</button>
          <button className="p-2 rounded-lg hover:bg-white/[0.04] text-aegis-mist cursor-pointer"><Settings className="w-4 h-4" /></button>
        </div>
      </motion.div>

      <motion.div variants={fadeInUp}>
        <GlassPanel animated={false}>
          <div className="space-y-1">
            {notifications.map((n, i) => (
              <div key={i} className={`flex items-start gap-4 p-4 rounded-xl transition-colors cursor-pointer ${n.read ? "hover:bg-white/[0.02]" : "bg-white/[0.02] hover:bg-white/[0.04]"}`}>
                {!n.read && <div className="w-2 h-2 rounded-full bg-aegis-cyan shrink-0 mt-2" />}
                <n.icon className={`w-5 h-5 shrink-0 mt-0.5 ${typeColors[n.type]}`} />
                <div className="flex-1 min-w-0">
                  <p className={`text-sm ${n.read ? "text-aegis-mist" : "text-aegis-cloud font-semibold"}`}>{n.title}</p>
                  <p className="text-xs text-aegis-slate mt-0.5">{n.desc}</p>
                  <span className="text-[10px] font-mono text-aegis-gunmetal mt-1 block">{n.time}</span>
                </div>
              </div>
            ))}
          </div>
        </GlassPanel>
      </motion.div>
    </motion.div>
  );
}
